EDITOR=nvim

alias aliases='$EDITOR $HOME/.bash_aliases && source $HOME/.bash_aliases'

alias c='clear'

alias heyapi='ssh bystander@192.168.40.14'
alias heyweb='ssh speedhunter@192.168.40.13'

alias i3conf='$EDITOR $HOME/.config/i3/config'
